In [1]:
import numpy as np
import pandas as pd

In [2]:
colnames=['id', 'sen1', 'sen2', 'num','var_y'] 
df = pd.read_csv('dataset_new.txt', sep='\t', lineterminator='\r',names=colnames, header=None)

In [3]:
df.head()

id                                               sen1  \
0   1  A group of kids is playing in a yard and an ol...   
1   2  A group of children is playing in the house an...   
2   3  The young boys are playing outdoors and the ma...   
3   5  The kids are playing outdoors near a man with ...   
4   9  The young boys are playing outdoors and the ma...   

                                                sen2  num       var_y  
0  A group of boys in a yard is playing and a man...  4.5     NEUTRAL  
1  A group of kids is playing in a yard and an ol...  3.2     NEUTRAL  
2  The kids are playing outdoors near a man with ...  4.7  ENTAILMENT  
3  A group of kids is playing in a yard and an ol...  3.4     NEUTRAL  
4  A group of kids is playing in a yard and an ol...  3.7     NEUTRAL

In [4]:
df.shape

(4500, 5)

In [5]:
df.describe()

id          num
count   4500.000000  4500.000000
mean    5018.431556     3.520946
std     2866.557215     1.025235
min        1.000000     1.000000
25%     2544.500000     3.000000
50%     5035.000000     3.692500
75%     7500.000000     4.300000
max    10000.000000     5.000000

In [6]:
df.dtypes

id         int64
sen1      object
sen2      object
num      float64
var_y     object
dtype: object

In [7]:
df = df.drop(['id','num'],axis = 1)

In [8]:
df.head()

sen1  \
0  A group of kids is playing in a yard and an ol...   
1  A group of children is playing in the house an...   
2  The young boys are playing outdoors and the ma...   
3  The kids are playing outdoors near a man with ...   
4  The young boys are playing outdoors and the ma...   

                                                sen2       var_y  
0  A group of boys in a yard is playing and a man...     NEUTRAL  
1  A group of kids is playing in a yard and an ol...     NEUTRAL  
2  The kids are playing outdoors near a man with ...  ENTAILMENT  
3  A group of kids is playing in a yard and an ol...     NEUTRAL  
4  A group of kids is playing in a yard and an ol...     NEUTRAL

In [9]:
import re

In [10]:
import nltk

In [11]:
from nltk.corpus import stopwords

In [12]:
def uncommon(a,b): 
  a=a.split() 
  b=b.split() 
  k=set(a).symmetric_difference(set(b)) 
  return k 

In [13]:
for i in df.index:
    temp = df['sen1'][i]
    temp2 =df['sen2'][i]
    df['sen1'][i]= list(uncommon(temp,temp2))

In [14]:
df.head()

sen1  \
0                              [old, boys, an, kids]   
1  [old, yard, an, kids, house, a, there, childre...   
2  [with, the, near, smiling, smile, boys, young,...   
3  [with, the, old, are, yard, is, an, background...   
4  [smiling, old, are, boys, young, yard, an, nea...   

                                                sen2       var_y  
0  A group of boys in a yard is playing and a man...     NEUTRAL  
1  A group of kids is playing in a yard and an ol...     NEUTRAL  
2  The kids are playing outdoors near a man with ...  ENTAILMENT  
3  A group of kids is playing in a yard and an ol...     NEUTRAL  
4  A group of kids is playing in a yard and an ol...     NEUTRAL

In [15]:
df['sen1'][1]

['old', 'yard', 'an', 'kids', 'house', 'a', 'there', 'children', 'no']

In [16]:
df.dtypes

sen1     object
sen2     object
var_y    object
dtype: object

In [17]:
for i in df.index:
    sentence = df['sen1'][i]
    df['sen1'][i] = ' '.join(sentence)

In [18]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['sen1'])

In [19]:
type(X)

scipy.sparse.csr.csr_matrix

In [20]:
X=X.toarray()

In [21]:
type(X)

numpy.ndarray

In [22]:
X.shape

(4500, 2085)

In [23]:
 y=df.iloc[:,-1]

In [24]:
y

0          NEUTRAL
1          NEUTRAL
2       ENTAILMENT
3          NEUTRAL
4          NEUTRAL
           ...    
4495       NEUTRAL
4496       NEUTRAL
4497       NEUTRAL
4498       NEUTRAL
4499       NEUTRAL
Name: var_y, Length: 4500, dtype: object

In [25]:
type(y)

pandas.core.series.Series

In [26]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,y,test_size=0.33,random_state=2)

In [27]:
xtrain.shape

(3015, 2085)

In [28]:
ytrain.shape

(3015,)

In [29]:
#naive Bayes
from sklearn.naive_bayes import GaussianNB
nv=GaussianNB()
nv.fit(xtrain,ytrain)

GaussianNB()

In [30]:
y_pred=nv.predict(xtest)

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(ytest,y_pred)

0.5346801346801346

In [32]:
from sklearn.metrics import *

In [33]:
f1_score(ytest,y_pred, average=None)

array([0.49709302, 0.38117107, 0.64776754])

In [34]:
precision_score(ytest,y_pred, average= None)

array([0.36538462, 0.37899543, 0.78929188])

In [35]:
#Knn
from sklearn.neighbors import KNeighborsClassifier
kc = KNeighborsClassifier()
kc.fit(xtrain,ytrain)

KNeighborsClassifier()

In [36]:
y_pred =kc.predict(xtest)

In [37]:
accuracy_score(ytest,y_pred)

0.5831649831649832

In [38]:
f1_score(ytest,y_pred, average=None)

array([0.70955166, 0.52408478, 0.58069063])

In [39]:
precision_score(ytest,y_pred, average= None)

array([0.62116041, 0.44958678, 0.70187394])

In [40]:
#random Forest
from sklearn.ensemble import RandomForestClassifier
rc = RandomForestClassifier()

In [41]:
rc.fit(xtrain,ytrain)

RandomForestClassifier()

In [42]:
y_pred = rc.predict(xtest)

In [43]:
accuracy_score(ytest,y_pred)

0.7818181818181819

In [44]:
f1_score(ytest,y_pred, average=None)

array([0.84454756, 0.67079208, 0.81802426])

In [45]:
precision_score(ytest,y_pred, average= None)

array([0.86255924, 0.72266667, 0.78754171])